// For licensing and usage information, read docs/winui_license.txt
// ============================================================================

// ============================================================================
//
// mkhelp.cpp
//
// Simple resource HIDC to Help entry tool.
//
// MSH - 20070815
//
// ============================================================================

// standard C++ headers
#include <memory>
#include <iomanip>
#include <iostream>
#include <fstream>
#include <vector>

// standard windows headers

// MAME headers
#include "osdcore.h"

// MAMEUI headers
#include "mui_cstr.h"

#include "mui_util.h"

static int compare( const void *arg1, const void *arg2 );
static void extract_help_ids(const char *buffer, FILE *fp);

// --------------------------------------------------------
// main - primary entry point
// --------------------------------------------------------

int main(int argc, char *argv[])
{
	const char *resourcefile, *varname, *type;
	std::ifstream ifs_source;
	std::ofstream ofs_destination;
	std::unique_ptr<char[]> buffer;
	int bytes;

	varname = "dwHelpIDs";
	type = "DWORD";

	if (argc < 2)
	{
		std::cerr << "Usage:\n  mkhelp <resource.rc>\n\n"
				  << "The default <type> is DWORD, with an assumed nullptr terminator pair\n";
		return 1;
	}

	// extract arguments
	resourcefile = argv[1];

	// open source file for reading, seek to the end immediately to find size
	ifs_source.open(resourcefile, std::ios::in | std::ios::ate | std::ios::binary);
	if (!ifs_source.is_open())
	{
		std::cerr << "Unable to open resource file '" << resourcefile << "'\n";
		return 1;
	}

	// determine file size
	bytes = ifs_source.tellg();
	ifs_source.seekg(0, ifs_source.beg);

	// allocate memory
	buffer = std::make_unique<char[]>(bytes + 1);
	if (!buffer)
	{
		ifs_source.close();
		std::cerr << "Out of memory allocating " << bytes << " byte buffer\n";
		return 1;
	}

	ifs_source.read(buffer.get(), bytes);
	buffer[bytes] = 0;
	ifs_source.close();

	// open dest file (creates or overwrites a file named "output.cpp")
	// ADJUST THIS: Change "output.cpp" to your desired output filename or argv[2]
	ofs_destination.open("output.cpp", std::ios::out | std::ios::trunc);
	if (!ofs_destination.is_open())
	{
		std::cerr << "Unable to open destination file for writing.\n";
		return 1;
	}

	// open dest file header layout
	ofs_destination << "// \n * Help ID array - Generated by mkhelp\n\n\n"
					<< "#include <windows.h>\n#include \"resource.h\"\n#include \"resource.hm\"\n\n"
					<< "extern const " << type << " " << varname << "[] = \n{\n";

	extract_help_ids(buffer.get(), ofs_destination);

	ofs_destination << "\n};" << "\n";

	// close the file
	ofs_destination.close();

	return 0;
}

static void extract_help_ids(const char* buffer, std::ofstream file_stream)
{
	const char* ptr = buffer;
	std::vector<std::string> help_ids;

	help_ids.reserve(500);
	while (*ptr)
	{
		if (mui_strncmp("HIDC_", ptr, 5) == 0)
		{
			std::string id_name;
			while (*ptr && *ptr != '\x0d' && *ptr != '\x0a')
				id_name += *ptr++;

			 if (!id_name.empty())
			  help_ids.push_back(id_name.substr(1));

		}
		else
			ptr++;
	}

	// Sort using quicksort algorithm:
	std::sort(help_ids.begin(), help_ids.end());

	// Now print them out.
	std::string last_ptr = "";
	for (const auto& id : help_ids) {
		if (id == last_ptr) {
			continue;
		}
		file_stream << "\t" << std::setw(30) << id << std::ws << "H" << id << "\n";
		last_ptr = id;
	}
	file_stream << "\t" << std::setw(30) << 0 << "," << 0;
}
